feat: add textField
frontzen/frontzen pull request #32
Opened 2023-01-08 10:58 UTC by Best-Sardar

2023-01-10 14:43 UTC, mdeljavan requested changes

2023-01-10 14:43 UTC, mdeljavan commented on libs/core/src/styles/createTheme.tsx
> +              }),
```suggestion
          paddingTop: theme.spacing(textFieldSpacing[ownerState.size]),
          paddingBottom: theme.spacing(textFieldSpacing[ownerState.size]),
```
textFieldSpacing or any naming that you like.

2023-01-10 14:43 UTC, mdeljavan commented on libs/core/src/formHelperText/FormHelperText.tsx
> +export const FormHelperText = styled(MuiFormHelperText, {
if you think this component is used in DS so export it from mui directory

2023-01-11 06:25 UTC, Best-Sardar commented on libs/core/src/utils.ts
> +export const expectProps = (notAllowed: string | string[]) => {
چرا ؟ اگه هم string بگیریم  آرایه ای، استفادش برامون راحت تر نیست ؟ معمولا استفادمون تکی هست.

2023-01-11 06:30 UTC, Best-Sardar commented on libs/core/src/palette/colors/warm/yellow.ts
> +
چرا نه ؟
به نظرم برای این که چشم راحت‌تر موارد رو پیدا کنه خوبه که بخش هایی کدی که از لحاظ معنایی تفکیک میشن رو جدا کنم.
الان اینجا من میخوایم یکی از رنگ دیزاین سیستم رو تعریف کنیم یه بخش mui ای داره که بالاست یه فاصله و بخش shade هاش.
البته که سلیقه ای هست اگه روی این موارد حساسیت خاصی هست بگین که یه بار صحبت کنیم.

2023-01-11 06:31 UTC, mdeljavan commented on libs/core/src/utils.ts
> +export const expectProps = (notAllowed: string | string[]) => {
ok

2023-01-11 06:35 UTC, mdeljavan commented on libs/core/src/palette/colors/warm/yellow.ts
> +
Ack

2023-01-18 07:47 UTC, mdeljavan approved these changes

2023-01-18 08:52 UTC, mdeljavan approved these changes

2023-01-18 09:30 UTC, merged