feat: buttonLink
frontzen/frontzen pull request #55
Opened 2023-01-21 11:25 UTC by alisajadih

2023-01-22 09:44 UTC, Best-Sardar requested changes

2023-01-22 09:44 UTC, Best-Sardar commented on design-system/core/src/styles/createTheme.tsx
> +            background: 'unset',
اینجا رو transparent کنیم بهتر نیست ؟

2023-01-22 09:44 UTC, Best-Sardar commented on design-system/core/src/styles/createTheme.tsx
>      MuiButton: {
اینا رو بچه‌ها بردن توی بخش‌های پوشه های خودشون قرار دادن بهتره برای button و fab هم این کار رو بکنیم

2023-01-22 09:44 UTC, Best-Sardar commented on design-system/core/src/styles/createTheme.tsx
> +                '& >*:nth-of-type(1)': {
اینا رو یه فاصله بدیم معنا دار تر بشه چندخط پایین تر هم داریم

2023-01-22 10:33 UTC, alisajadih commented on design-system/core/src/button/Button.tsx
> +export const Button = (props: ButtonProps) => (
i prefer to not use React.FC
https://medium.com/raccoons-group/why-you-probably-shouldnt-use-react-fc-to-type-your-react-components-37ca1243dd13

2023-01-22 10:33 UTC, alisajadih commented on design-system/core/src/button/Fab.tsx
> +export const Fab = (props: FabProps) => (
same

2023-01-22 10:37 UTC, alisajadih commented on design-system/core/src/button/index.ts
> +export { Fab } from './Fab';
I don't think. we should double check about mui folder. I think core/index.ts should export all designsystem components

2023-01-22 10:38 UTC, alisajadih commented on libs/core/src/button/Button.tsx
> +import { Button as MuiButton, ButtonProps } from '@mui/material';
No, we need Button component now. because we should disable ripple effect of button when using link variant

2023-01-22 10:42 UTC, alisajadih commented on design-system/core/src/styles/createTheme.tsx
>              padding: 4,
No. We could not agree on spacing usage. I assume that we should be explicit about padding and width and height. but use spacing in margins as much as we can

2023-01-22 10:43 UTC, alisajadih commented on design-system/core/src/button/Button.stories.tsx
> +    <>
fixed

2023-01-22 10:48 UTC, alisajadih commented on design-system/core/src/styles/createTheme.tsx
> +            background: 'unset',
fixed

2023-01-22 10:48 UTC, alisajadih commented on design-system/core/src/styles/createTheme.tsx
>      MuiButton: {
let's do it in separate pr

2023-01-22 10:50 UTC, alisajadih commented on design-system/core/src/button/Button.tsx
> +import { Button as MuiButton, ButtonProps } from '@mui/material';
fixed

2023-01-22 10:50 UTC, alisajadih commented on design-system/core/src/styles/createTheme.tsx
> +                '& >*:nth-of-type(1)': {
where ?

2023-01-22 12:09 UTC, alisajadih commented on libs/core/src/button/Button.tsx
> +import { Button as MuiButton, ButtonProps } from '@mui/material';
done

2023-01-22 12:16 UTC, alisajadih commented on design-system/core/src/styles/createTheme.tsx
> +                filter: `drop-shadow(0px 0px 10px ${alpha(getColorFromThemeWithColorProps(theme, ownerState), 0.7)})`,
ok

2023-01-23 07:19 UTC, Best-Sardar approved these changes

2023-01-23 08:14 UTC, Best-Sardar approved these changes

2023-01-23 08:45 UTC, Best-Sardar approved these changes

2023-01-23 08:49 UTC, merged