feat: add default palette color for buttons
frontzen/frontzen pull request #89
Opened 2023-02-26 14:07 UTC by alisajadih

2023-03-04 09:11 UTC, Best-Sardar requested changes

2023-03-04 09:11 UTC, Best-Sardar commented on design-system/core/src/palette/palette.ts
> +  default: defaultPalette,
اینم طیق صحبتی که کردیم تغییرش بدیم

2023-03-06 06:21 UTC, alisajadih commented on design-system/core/src/button/Button.stories.tsx
> +    </Box>
later we should implement storybook.

2023-03-06 06:22 UTC, alisajadih commented on design-system/core/src/button/buttonThemePart.tsx
> +  interface FabPropsColorOverrides {}
no

2023-03-13 11:27 UTC, Best-Sardar commented on design-system/core/src/button/Button.stories.tsx
> +    </Box>
ok

2023-03-13 11:50 UTC, Best-Sardar submitted a review, later dismissed

2023-03-14 05:57 UTC, Best-Sardar approved these changes

2023-03-14 06:40 UTC, merged